### ISSUE TITLE
Input does not meet YAML 1.2 "Core Schema" specification: create_ref

### ISSUE THREAD

**Issue by maggie0002** [balena-io/deploy-to-balena-action#77] opened 2021-12-24 11:27 UTC
Started getting this error today:

```
Input does not meet YAML 1.2 "Core Schema" specification: create_ref
Support boolean input list: `true | True | TRUE | false | False | FALSE`
```

Prevents the workflow from completing successfully. 
```

[Info]        Build finished in 6 minutes, 45 seconds
1749

1750

1751
			    \
1752
			     \       .,-.@
1753
			      \\   .^xxx-
1754
			       \\,xxxxx;
1755
			        >  xxx/
1756
			    _.-(6'  xx
1757
			   (=___._/` \
1758
			        )  \ |
1759
			       /   / |
1760
			      /    > /
1761
			     j    < _\
1762
			 _.-' :      ``.
1763
			 \ r=._\        `.
1764
			<`\\_  \         .`-.
1765
			 \ r-7  `-. ._  ' .  `\
1766
			  \`,      `-.`7  7)   )
1767
			   \/         \|  \'  / `-._
1768
			              ||    .'
1769
			               \\  (
1770
			                >\  >
1771
			            ,.-' >.'
1772
			           <.'_.'
1773
			             <'
1774
			
1775

1776
Build process exit
1777

1778

1779
Error: Input does not meet YAML 1.2 "Core Schema" specification: create_ref
1780
Support boolean input list: `true | True | TRUE | false | False | FALSE`
```

```
      - name: Deploy aarch64 to development
        uses: balena-io/deploy-to-balena-action@master
        id: build-dev-aarch64
        with:
          balena_token: ${{ secrets.BALENA_API_TOKEN }}
          fleet: myfleet/myfleet
```

**Comment by klutchell** [comment] 2021-12-24 11:46
Hey @maggie0002 , that must be related to https://github.com/balena-io/deploy-to-balena-action/pull/76 but I didn't see this error in testing. Do you have either `create_ref` or `create_tag` defined in your YAML? Maybe this happens if neither are set so it sounds like a bug.

**Comment by maggie0002** [comment] 2021-12-24 11:54
> Hey @maggie0002 , that must be related to https://github.com/balena-io/deploy-to-balena-action/pull/76 but I didn't see this error in testing. Maybe this happens if neither are set so it sounds like a bug.

I noticed https://github.com/balena-io/deploy-to-balena-action/pull/76 and seemed too coincidental to not be somehow related. Although it seemed like a straight swap for terms. 

Only other reference I found was here:

https://github.com/balena-io/deploy-to-balena-action/blob/ea289f44e36c43d7ff9500a0557c630a05d0a67b/src/action.ts#L99

After seeing https://github.com/balena-io/deploy-to-balena-action/pull/76 I didn't investigate my setup, made an assumption it was most likely upstream and slung the issue here.

**Comment by klutchell** [comment] 2021-12-24 12:09
The issue seems to be that `getBooleanInput` allows the option required=false, but still tries to validate that the return value is a true boolean. Since I haven't defined a default for `create_ref` it is returning an empty string and this function is failing.

https://github.com/actions/toolkit/blob/daf8bb00606d37ee2431d9b1596b88513dcf9c59/packages/core/src/core.ts#L171-L181

I fixed it in the above PR by not validating boolean, and allowing truthy to interpret it if it's set.

**Comment by klutchell** [comment] 2021-12-24 12:20
Hey @maggie0002, it seems to be fixed now. I reproduced it on a repo of my own and confirmed that the PR above avoids the error. Thanks for catching this!

**Closed** 2021-12-24 12:19 UTC
